spring:
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  profiles:
    active: dev

myblog:
  comment:
    avatar: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzNLOaKxZHNx5eVbVjIAnft5fHEmI_KjofnQ&usqp=CAU