spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 888888
    driver-class-name: com.mysql.cj.jdbc.Driver
#下面这些内容是为了让MyBatis映射
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml              #指定Mybatis的Mapper文件
  type-aliases-package: com.hnie.blogbackstage.mybatis.entity   #指定Mybatis的实体目录
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl       #用于控制台打印sql语句
logging:
  level:
    root: warn
    com.hnie: info
  file:
    name: log/blog.log

myblog:
  comment:
    avatar: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzNLOaKxZHNx5eVbVjIAnft5fHEmI_KjofnQ&usqp=CAU
server:
  port: 80


